### ISSUE TITLE
Error: Failed to get gigs details  when loading the gigs details page

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-gigs-app#43]
Error: Failed to get gigs details  when loading the gigs details page. This issue is intermittent .
<img width="1440" alt="Screenshot 2021-11-01 at 9 03 01 AM" src="https://user-images.githubusercontent.com/58783823/139624309-415a0f15-7fd3-4079-9f12-60f5f57cc59d.png">

https://user-images.githubusercontent.com/58783823/139624301-9af8f791-391a-49ff-a26c-57887630d685.mov

**Comment by LieutenantRoger** [comment]
I seems not able to reproduce this

**Comment by vikasrohit** [comment]
I saw something similar yesterday when trying to setup the gigs app locally.

**Comment by LieutenantRoger** [comment]
I have been able to reproduce this issue, it's caused by large cookie sent along with the request of getting job detail info.

The challenges-app will generate a lot of cookies, so if you visit some challenges, the cookie data will be large, the token data is also very large .

I have doubled the limitation of a request header size for the server.  It should be enough now

**Comment by codejamtc** [comment]
I can't reproduce it anymore hence marking it as `Pass`

https://user-images.githubusercontent.com/42398485/140913399-6c5433e8-5cd1-4082-bd26-fd8d024b377c.mp4

**Comment by SathyaJayabal** [comment]
not reproducible
